### ISSUE TITLE
"ssl" keyword replaced with "tls" in [SERVER] section

### ISSUE THREAD

**Issue by J-Siu** [monkey/monkey#224]
In [SERVER] section, "ssl" keyword has no effect and will not load/activate tls plugin. Need to use "tls" instead.

Following no longer works:
```
[SERVER]
    Listen 443 ssl
```
Following works:
```
[SERVER]
    Listen 443 tls
```

http://monkey-project.com/documentation/1.6/plugins/tls.html need update.

**Comment by edsiper** [comment]
In order to clarify. Monkey code in GIT master, belongs to the development version of the new 1.7 series, for hence it have many changes which may not be compatible with the current 1.6.x stable branch.

The documentation that you are seeing belongs to Monkey v1.6 where in order to enable encryption on the listener you have to use the 'ssl' option, you can see the reference here in the source code:

   https://github.com/monkey/monkey/blob/1.6/mk_server/mk_config.c#L243

The option 'tls' is new and will only work for Monkey 1.7, the documentation for that version is not yet available as the version is still under development.
